let sideBar = document.querySelector('#sideBar');
let mostrarMais = document.querySelector('#mostrarMais')
let mostrarMenos = document.querySelector('#mostrarMenos')
let conta = document.querySelector('#conta')
let inicio = document.querySelector('#inicio')
let meuPerfil = document.querySelector('#meuPerfil')
let calendario = document.querySelector('#calendario')
let grafico = document.querySelector('#grafico')
let notificacao = document.querySelector('#notificacao')
let configuracao = document.querySelector('#configuracao')
let sair = document.querySelector('#sair')

let labelInicio = document.querySelector('#labelInicio')
let labelPaciente = document.querySelector('#labelPaciente')
let labelCalendario = document.querySelector('#labelCalendario')
let labelGrafico = document.querySelector('#labelGrafico')
let labelNotificacao = document.querySelector('#labelNotificacao')
let labelConfiguracao = document.querySelector('#labelConfiguracao')
let labelconta = document.querySelector('#labelconta')
let labelSair = document.querySelector('#labelSair')


function mostrarMa(){
    mostrarMais.setAttribute('style', 'display: none;')
    mostrarMenos.setAttribute('style', 'display: flex; left: 250px;')
    sideBar.setAttribute('style', 'width: 250px; animation: aparecer1 .4s;')

    conta.setAttribute('style', 'width: 200px; animation: aparecer5 .4s;')
    inicio.setAttribute('style', 'width: 210px; border-radius: 40px; animation: aparecer5 .4s;')
    meuPerfil.setAttribute('style', 'width: 210px; border-radius: 40px; animation: aparecer5 .4s;')
    calendario.setAttribute('style', 'width: 210px; border-radius: 40px; animation: aparecer5 .4s;')
    grafico.setAttribute('style', 'width: 210px; border-radius: 40px; animation: aparecer5 .4s;')
    notificacao.setAttribute('style', 'width: 210px; border-radius: 40px; animation: aparecer5 .4s;')
    configuracao.setAttribute('style', 'width: 210px; border-radius: 40px; animation: aparecer5 .4s;')
    sair.setAttribute('style', 'width: 200px; animation: aparecer5 .4s;')
    labelInicio.setAttribute('style', 'display: flex; animation: aparecer5 .1s;')
    labelPaciente.setAttribute('style', 'display: flex;')
    labelCalendario.setAttribute('style', 'display: flex;')
    labelGrafico.setAttribute('style', 'display: flex;')
    labelNotificacao.setAttribute('style', 'display: flex;')
    labelConfiguracao.setAttribute('style', 'display: flex;')
    labelconta.setAttribute('style', 'display: flex;')
    labelSair.setAttribute('style', 'display: flex;')

}
function mostrarMe(){
    mostrarMais.setAttribute('style', 'display: flex;')
    mostrarMenos.setAttribute('style', 'display: none;')
    sideBar.setAttribute('style', 'width: 65px;  animation: aparecer2 .4s;')
   
    conta.setAttribute('style', 'width: 50px; transition: none;')
    inicio.setAttribute('style', 'width: 50px; transition: none;')
    meuPerfil.setAttribute('style', 'width: 50px ;transition: none;')
    calendario.setAttribute('style', 'width: 50px;transition: none;')
    grafico.setAttribute('style', 'width: 50px;transition: none;')
    notificacao.setAttribute('style', 'width: 50px;transition: none;')
    configuracao.setAttribute('style', 'width: 50px;transition: none; ')
    sair.setAttribute('style', 'width: 50px;transition: none;')
    labelInicio.setAttribute('style', 'display: none;')
    labelPaciente.setAttribute('style', 'display: none;')
    labelCalendario.setAttribute('style', 'display: none;')
    labelGrafico.setAttribute('style', 'display: none;')
    labelNotificacao.setAttribute('style', 'display: none;')
    labelConfiguracao.setAttribute('style', 'display: none;')
    labelconta.setAttribute('style', 'display: none;')
    labelSair.setAttribute('style', 'display: none;')
}